spring.application.name=payment-service
spring.profiles.active=${SPRING_PROFILES_ACTIVE}

server.port=${APP_PORT}

random.api.url=https://www.random.org/integers/?num=1&min=1&max=100&col=1&base=10&format=plain&rnd=new

spring.data.mongodb.uri=${MONGO_DB_URI}
spring.data.mongodb.database=payment_db
spring.data.mongodb.auto-index-creation=false

spring.liquibase.enabled=true
spring.liquibase.change-log=db/changelog/db.changelog-master.json

kafka.topics.producer=${PRODUCER_TOPIC}

spring.kafka.bootstrap-servers=${BOOTSTRAP_SERVER}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
